import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Container from './components/container';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'linear.app Clone',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <Container>header here</Container>
        </header>
        <main>
          <Container>{children}</Container>
        </main>
        <footer>
          <Container>footer here</Container>
        </footer>
      </body>
    </html>
  );
}
